INSERT INTO FOODS (ID, NAME, CALORIES, FAT, PROTEIN, CARBS)
VALUES (1, 'apple', 95, 0, 0, 25);

INSERT INTO FOODS (ID, NAME, CALORIES, FAT, PROTEIN, CARBS)
VALUES (2, 'banana', 110, 0, 1, 30);

INSERT INTO FOODS (ID, NAME, CALORIES, FAT, PROTEIN, CARBS)
VALUES (3, 'potato chips', 160, 10, 2, 15);